---
- name: Create downloads and resources directories
  file:
    path="{{ item }}"
    state=directory
    mode=0755
  with_items:
    - "{{ download_dir }}"
    - "{{ bin_dir }}"
    - "{{ image_dir }}"

- name: Get kubernetes binary
  get_url:
    url="https://storage.googleapis.com/kubernetes-release/release/v{{ kube_version }}/bin/linux/amd64/hyperkube"
    dest="{{ bin_dir }}/hyperkube"
    mode=0755

- name: Get etcd tar file
  get_url:
    url="https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest="{{ download_dir }}/etcd-v{{ etcd_version }}-linux-amd64"

- name: Extract etcd tar file
  unarchive:
    src="{{ download_dir }}/etcd-v{{ etcd_version }}-linux-amd64"
    dest="{{ download_dir }}"

- name: Move etcd bin to resources directory
  copy:
    src="{{ download_dir }}/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}"
    dest="{{ bin_dir }}/{{ item }}"
    mode=0755
  with_items:
    - etcd
    - etcdctl

- include: get-image.yml
  when: not net_install
