---
- name: Copy k8s-deploy.tar.gz to remote machines
  unarchive:
    src=k8s-deploy.tar.gz
    dest=/opt

- name: Extract kubernetes
  unarchive:
    src="/opt/k8s-deploy/kubernetes-v{{ kube_version }}-linux-amd64.tar.gz"
    dest=/opt
    copy=no

- name: Extract etcd
  unarchive:
    src="/opt/k8s-deploy/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest=/opt
    copy=no

- name: Extract images
  unarchive:
    src=/opt/k8s-deploy/docker-images.tar.gz
    dest=/opt
    copy=no

# nsenter is in util-linux package, but it's not included in ubuntu-14.04.
# This binary is copied from hyperkube image
- name: Extract nsenter
  unarchive:
    src="/opt/k8s-deploy/nsenter-{{ nsenter_version }}-linux-amd64.tar.gz"
    dest=/opt
    copy=no
