---
- name: Update cache
  apt: update_cache=yes

- name: Install essentials packages
  apt:
    name='{{ item }}'
    state=present
    install_recommends=no
  with_items:
    - apt-transport-https
    - ca-certificates
    - socat
    - rsync
    - util-linux                # nsenter
  when: ansible_os_family == 'Debian'

- include: install-docker.yml
