---
- name: Make sure directory exist
  file: path={{ item }} state=directory mode=0755 recurse=yes
  with_items:
    - /opt/bin
    - /opt/cni/bin
    - /etc/kubernetes/manifests
    - /etc/cni/net.d

- name: Make sure /etc/kubernetes/certs directory exist
  file: path=/etc/kubernetes/certs state=directory mode=0750 group=k8s

- name: Install hyperkube
  file:
    src="/opt/kubernetes-v{{ kube_version }}-linux-amd64/hyperkube"
    dest=/opt/bin/hyperkube
    state=link
    force=yes
    mode=0755

- name: Install nsenter
  file:
    src="/opt/nsenter-{{ nsenter_version }}-linux-amd64/nsenter"
    dest=/usr/local/bin/nsenter
    state=link
    force=yes
    mode=0755
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 15

- name: Set fact of IP
  set_fact:
    node_ip: "{% if public_iface %}{{ hostvars[inventory_hostname]['ansible_'+public_iface]['ipv4']['address'] }}{% else %}{{ ansible_default_ipv4 }}{% endif %}"

- name: Generate kube-node certificates
  command: "/opt/bin/cert-generator.sh {{ node_ip }} {{ ansible_hostname }}"
  delegate_to: "{{ groups['masters'][0] }}"

- name: Copy certificates # Note: This requires rsync installed and ssh with ssh key
  synchronize:
    src="/etc/kubernetes/certs/{{ item }}"
    dest="/etc/kubernetes/certs/{{ item }}"
    mode=push
    rsync_path="sudo rsync"
  with_items:
    - ca.crt
    - "{{ node_ip }}.crt"
    - "{{ node_ip }}.key"
  delegate_to: "{{ groups['masters'][0] }}"

- name: Symlink certificates
  file:
    src="/etc/kubernetes/certs/{{ node_ip }}.{{ item }}"
    dest="/etc/kubernetes/certs/kubelet.{{ item }}"
    state=link
    force=yes
    mode=0600
  with_items:
    - key
    - crt

- include: load-image.yml
  when: not net_install

- include: configure.yml
  tags:
    - configure

- include: start.yml
  when: kube_modified == true

- include: restart.yml
  when: kube_modified == true and kube_started.changed == false
  tags:
    - restart
